// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using timeTrackingSystemBackend.Entities;

namespace timeTrackingSystemBackend.Migrations
{
    [DbContext(typeof(WebApiDatabaseContext))]
    [Migration("20200421143300_WebApiDatabaseContext")]
    partial class WebApiDatabaseContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("timeTrackingSystemBackend.Entities.Tunnit", b =>
                {
                    b.Property<int>("TunnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TunnitID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LuokkahuoneId")
                        .IsRequired()
                        .HasColumnName("LuokkahuoneID")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<int?>("OppilasId")
                        .HasColumnName("OppilasID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Sisaan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Ulos")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("int");

                    b.HasKey("TunnitId");

                    b.HasIndex("OppilasId");

                    b.HasIndex("TunnitId")
                        .HasName("IX_tunnit");

                    b.ToTable("tunnit");
                });

            modelBuilder.Entity("timeTrackingSystemBackend.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("timeTrackingSystemBackend.Entities.Tunnit", b =>
                {
                    b.HasOne("timeTrackingSystemBackend.Entities.Users", "Oppilas")
                        .WithMany("Tunnit")
                        .HasForeignKey("OppilasId")
                        .HasConstraintName("FK_tunnit_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
